### ISSUE TITLE
NameError: name 'time_t' is not defined Mac OS X

### ISSUE THREAD

**Issue by zachzeid** [the-tcpdump-group/libpcap#744]
Unable to import libpcap without running into this error:
>>> import libpcap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zachary.zeid/.pyenv/versions/dlproxy-3.6.1/lib/python3.6/site-packages/libpcap/__init__.py", line 7, in <module>
    from ._pcap import *
  File "/Users/zachary.zeid/.pyenv/versions/dlproxy-3.6.1/lib/python3.6/site-packages/libpcap/_pcap.py", line 74, in <module>
    from ._platform import is_windows, is_linux, defined
  File "/Users/zachary.zeid/.pyenv/versions/dlproxy-3.6.1/lib/python3.6/site-packages/libpcap/_platform/__init__.py", line 35, in <module>
    from ._osx     import DLL_PATH, DLL, CFUNC, dlclose
  File "/Users/zachary.zeid/.pyenv/versions/dlproxy-3.6.1/lib/python3.6/site-packages/libpcap/_platform/_osx/__init__.py", line 38, in <module>
    class timeval(ct.Structure):
  File "/Users/zachary.zeid/.pyenv/versions/dlproxy-3.6.1/lib/python3.6/site-packages/libpcap/_platform/_osx/__init__.py", line 40, in timeval
    ("tv_sec",  time_t),       # seconds
NameError: name 'time_t' is not defined

**Comment by agnosticdev** [comment]
It looks like Python cannot find sys/time.h on OSX.
Taken from:
```c
include <time.h>

 struct timeval {
     time_t      tv_sec;   /* Seconds. */
     suseconds_t tv_usec;  /* Microseconds. */
 };
```

What version of OS X are you running?
Also, it looks like you are running a custom version of Python 3.6 in a virtual environment, is that correct?

**Comment by zachzeid** [comment]
I'm running High Sierra v10.13.6.  I'm just running 3.6.1 in a pyenv, it's the default installation.

**Comment by guyharris** [comment]
That's an issue with Python's libpcap package, not with libpcap; libpcap itself works Just Fine.
